### ISSUE TITLE
노노그램 이번한주문제

### ISSUE THREAD

**Issue by 0svvin** [deunlee/Nonogram-Solver#1]
30 30

4 2 6 10 3
5 2 7 9 1 1
3 2 6 12
5 1 8 1 1 2
2 11 1
4 4 5 3 2
5 2 10 1 4 2
6 2 1 1 1 4 4 
3 1 5 3
4 2 1 5 2 
4 2 2 5 1
4 3 5 5 2
3 7 5 5
3 2 11 2
4 1 4 5 4
3 5 4 2
3 7 4 3
5 1 1 8 3 4
5 4 4 1 1 10
5 2 1 4 6 5
5 5 1 4 1 6
5 1 7 1 1 3
3 2 6 2
4 1 6 3 1
4 7 2 1 2
5 2 4 2 3 2
4 7 2 4 3
4 1 14 3 3
4 1 4 9 4
5 1 1 1 10 4

4 4 2 3 3
3 3 2 1
1 1
1 10
2 3 12
4 2 4 7 4
5 7 1 1 1 9
4 7 3 10 1
5 5 2 2 7 1
4 5 1 5 6
5 5 2 2 4 3
5 6 4 4 4 3
5 3 3 5 4 3
7 1 1 3 2 4 1 5 
4 3 3 9 4
5 3 1 2 6 3
4 3 9 3
6 4 1 1 3 1 1
4 3 2 2 3
4 4 10 2 4
4 3 9 2 4
3 3 15 3
3 3 13 2
5 1 9 3 1 1
5 6 1 1 2 1
5 1 1 1 1 5
3 1 3 5
5 2 3 4 5 2
4 1 8 7 4
6 1 4 1 3 3 4

**Comment by 0svvin** [comment]
이거 정답쫌

**Comment by deunlee** [comment]
중간에 한 줄 틀린것 같네요. `4 3 9 3` -> `3 3 9 3`

![answer](https://user-images.githubusercontent.com/54697735/192924733-6e41f99a-c1a0-4194-be2b-5da30925a42f.png)

**Comment by 0svvin** [comment]
2022년 9월 29일 (목) 오전 11:28, Deun Lee ***@***.***>님이 작성:
